---
- name: Download Anaconda
  ansible.builtin.get_url: 
    url: '{{ anaconda_download_url }}'
    dest: /home/{{ username }}/Downloads/anaconda.sh
    checksum: ' {{ anaconda_download_checksum }}'
